name: create-pull-request-staging
on:
  push:
    branches-ignore:
      - main
      - production
      - staging
      - cpr/**

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      ###################################
      # Setup
      ###################################
      - uses: actions/checkout@v3
        with:
          ref: staging
      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Reset branch
        run: |
          git fetch origin ${{ github.ref_name }}:${{ github.ref_name }} --update-head-ok
          git reset --hard ${{ github.ref_name }}

      ###################################
      # Get the latest commit title
      ###################################
      - name: Get last commit
        run: echo "COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      ###################################
      # Create pull request
      ###################################
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: cpr/${{ github.ref_name }}
          title: ${{ env.COMMIT_TITLE }}
          delete-branch: true
          signoff: true
          body: |
          labels: |
            autoPR
          token: ${{ secrets.PAT }}
